change-template: '- $TITLE (by @$AUTHOR in #$NUMBER)'
prerelease: true
prerelease-identifier: 'b'
include-pre-releases: true
categories:

  - title: "⚠ Breaking Changes"
    labels:
      - 'breaking-change'

  - title: "🚀 New Providers"
    labels:
      - 'new-provider'

  - title: "🚀 Features"
    labels:
      - 'feature'
      - 'enhancement'
      - 'new-feature'

  - title: "🐛 Bugfixes"
    labels:
      - 'bugfix'

  - title: '🧰 Maintenance and dependency bumps'
    collapse-after: 3
    labels:
      - 'ci'
      - 'documentation'
      - 'maintenance'
      - 'dependencies'

template: |

  $CHANGES

  
  ## :bow: Thanks to our contributors

  Special thanks to the following contributors who helped with this release:

  $CONTRIBUTORS



