change-template: '- $TITLE (by @$AUTHOR in #$NUMBER)'

# Note: prerelease flag is set dynamically by the workflow based on channel
# This config is used for all release channels (stable, beta, nightly)

# Exclude bots from contributors list
exclude-contributors:
  - dependabot
  - dependabot[bot]
  - github-actions
  - github-actions[bot]
  - music-assistant-machine

categories:

  - title: "⚠ Breaking Changes"
    labels:
      - 'breaking-change'

  - title: "🚀 New Providers"
    labels:
      - 'new-provider'

  - title: "🚀 Features and enhancements"
    labels:
      - 'feature'
      - 'enhancement'
      - 'new-feature'

  - title: "🐛 Bugfixes"
    labels:
      - 'bugfix'

  - title: '🧰 Maintenance and dependency bumps'
    collapse-after: 3
    labels:
      - 'ci'
      - 'documentation'
      - 'maintenance'
      - 'dependencies'

template: |

  $CHANGES


  ## :bow: Thanks to our contributors

  Special thanks to the following contributors who helped with this release:

  $CONTRIBUTORS
